FROM ubuntu:22.04

WORKDIR /backend

RUN apt-get update && apt-get install -y python3 python3-pip curl net-tools

COPY ./backend .
COPY ./requirements.txt .
RUN pip3 install -r requirements.txt

CMD [ "python3", "main.py" ]
EXPOSE 8000