version: '3.8'

services:
  backend:
    build:
      context: .
      dockerfile: Dockerfile_Backend
    volumes:
      - ./backend/db-presentation.sqlite3:/backend/db-presentation.sqlite3
    ports:
      - "8000:8000"
    command: ["python3", "main.py"]

  frontend:
    build:
      context: .
      dockerfile: Dockerfile_Frontend
    volumes:
      - ./frontend2/.env:/frontend/.env
    ports:
      - "8081:8081"
      - "19000:19000"
      - "19001:19001"
      - "19002:19002"
    command: ["npx", "expo", "start"]
    tty: true