FROM ubuntu:22.04

WORKDIR /frontend

RUN apt-get update && apt-get install -y python3 python3-pip curl net-tools

RUN curl -fsSL https://deb.nodesource.com/setup_16.x | bash - \
    && apt-get install -y nodejs

RUN npm install -g expo-cli

COPY ./frontend2 .
RUN npm install

CMD [ "npx", "expo", "start" ]
EXPOSE 8081